#!/usr/bin/env node

var spawn = require('child_process').spawn;

run('npm test');

function run(args) {
  args = args.split(' ');
  var cmd = args.shift();
  var ch = spawn(cmd, args);
  ch.stdout.pipe(process.stdout);
  ch.stderr.pipe(process.stderr);
  ch.on('exit', function (code) {
    if(code) process.exit(code);
    var end = !ch.emit('next');
  });
  return ch;
}

/* vim: set sw=2 ts=2 et tw=80 ft=javascript : */
