#!/usr/bin/env node
/*jshint node:true*/
/*globals console:true */
'use strict';

var fs = require('fs')
  , luaparse = require('../')
  , options = { scope: true }
  , indent = '  '
  , verbose = true
  , testName
  , snippets = []
  // A list of notifications to display at the end of the scaffolding
  , notifications = []
  , intro = [
      "(function (root) {"
    , "  var freeExports = typeof exports === 'object' && exports"
    , "    , freeModule = typeof module === 'object' && module && module.exports == freeExports && module"
    , "    , freeGlobal = typeof global === 'object' && global;"
    , ""
    , "  if (freeGlobal.global == freeGlobal) root = freeGlobal;"
    , ""
    , "  var tests = "
  ].join('\n')
  , outro = [
      ";"
    , ""
    , "  if (typeof define === 'function' && typeof define.amd === 'object' && define.amd) {"
    , "    define(function() { return tests; });"
    , "  } else if (freeExports && !freeExports.nodeType) {"
    , "    if (freeModule) freeModule.exports = tests; // In Node.js or Ringo v0.8.0+"
    , "    else { // In Narwhal or RingoJS v0.7.0-"
    , "      for (var test in tests) if (tests.hasOwnProperty(test)) {"
    , "         freeExports[test] = tests[test];"
    , "      }"
    , "    }"
    , "  } else { // In Rhino or web browser"
    , "    if (!root.testSuite) root.testSuite = {};"
    , "    root.testSuite['%NAME%'] = tests;"
    , "  }"
    , "}(this));"
  ].join('\n');


// Scaffold content of a test file. If no test name is specified, simply return
// the tests as objects.
function scaffoldFile() {
  // Scaffold the test
  var expected = JSON.stringify(scaffoldTest(), null, indent)
    , firstline;
  if (!testName) return expected;

  // The frist line should not be indented so we separate it from the result.
  expected = expected.split('\n');
  firstline = expected.splice(0, 1);
  expected = expected.join('\n');

  return intro +
    firstline + '\n' +
    expected.replace(/^([\s\S])/gm, indent + "$1") +
    outro.replace(/%NAME%/, testName);
}

// Scaffold the test
function scaffoldTest() {
  var output = {};

  // Iterate over all snippets and generate their tests.
  snippets.forEach(function(snippet) {
    // Skip lines beginning with //
    if (/^\/\//.test(snippet)) return;

    // Convert to real escape sequences.
    snippet = snippet.replace(/\\n/g, '\n')
      .replace(/\\r/g, '\r')
      .replace(/\\t/g, '\t')
      .replace(/\\f/g, '\f')
      .replace(/\\v/g, '\v');

    // Generate the assertion.
    var result = scaffoldTestAssertion(snippet);

    // Remove the trailing FAIL flag as this will later be parsed as is by the
    // test suite. To identify failing tests we will check the type of the
    // expected result, an object is an assertion, while a string is a thrown
    // error.
    snippet = snippet.replace(/\s*-- FAIL\s*$/, '');
    output[snippet] = result;
  });

  // If a test name is used, wrap it around the test cases.
  if (testName) {
    var temp = {};
    temp[testName] = output;
    output = temp;
  }

  return output;
}

// Scaffold a test case.
function scaffoldTestAssertion(snippet) {
  var name = snippet // Store the original name with the FAIL flag.
    , expected
    , success = true;

  if (/-- FAIL\s*$/.test(snippet)) {
    snippet = snippet.replace(/\s*-- FAIL\s*$/, '');
    try {
      luaparse.parse(snippet, options);
      // For some reason it didnt throw a error.
      notifications.push('\x1B[33mExpected failure: \x1B[0m' + name);
    } catch (exception) {
      expected = exception.message;
    }
  } else {
    try {
      expected = luaparse.parse(snippet, options);
    } catch (exception) {
      notifications.push('\x1B[31m' + exception + ':\x1B[0m ' + name);
      success = false;
    }
  }

  if (verbose && !success) return '';

  return expected;
}

// Main ---------------------------------------------------

var args = process.argv.splice(2);

if (!args.length) {
  console.log([
      "Usage:"
    , "\tscaffold-test [snippet|file]..."
    , "\tscaffold-test \"locale foo = \\\"bar\\\"\""
    , "\tscaffold-test ./tests"
    , "\nOptions:"
    , "\t--ignore-errors"
  ].join('\n'));
  return;
}

var previous;
args.forEach(function(arg, index) {
  if (/^--ignore-errors/.test(arg)) return verbose = false;

  // Argument flags
  if (/^--name=/.test(arg)) {
    testName = arg.replace(/^--name=/, '');
    return;
  }

  // Snippet
  if (!fs.existsSync(arg)) {
    snippets.push(arg);
  }
  // File
  else {
    fs.readFileSync(arg, 'utf8')
      .split("\n")
      .forEach(function(snippet) {
        if (!snippet.length) return;
        snippets.push(snippet.replace(/\n$/, ''));
      });
  }
  return;
});

console.log(scaffoldFile());

if (verbose && notifications.length) {
  console.log("\nNotices: \n-----------------------------");
  notifications.forEach(function(notice) {
    console.log(notice);
  });
}

/* vim: set sw=2 ts=2 et tw=80 ft=javascript : */
